production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
development:
  sessions:
    default:
      database: mongo_profiler_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: mongo_profiler_test
      hosts:
        - localhost:27017
